package algonquin.cst2335.androidapplicationproject;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

/**
 * The Entity or Data Transfer Object of articles
 */
@Entity
public class XingyunArticle {

    /**
     * The autogenerated primary key for the entity
     */
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    public int id;

    /**
     * the headline column of the article entity
     */
    @ColumnInfo(name = "headline")
    protected String headline;

    /**
     * the url column of the article entity
     */
    @ColumnInfo(name = "url")
    protected String url;

    /**
     * the publication date column of the article entity
     */
    @ColumnInfo(name = "date")
    protected String date;

    /**
     * the Constructor for the XingyunArticle class
     * 
     * @param headline headline
     * @param url url
     * @param date date
     */
    public XingyunArticle(String headline, String url, String date) {
        this.headline = headline;
        this.url = url;
        this.date = date;
    }

    /**
     * the getter for headline
     * 
     * @return headline
     */
    public String getHeadline() {
        return headline;
    }

    /**
     * the getter for URL
     * 
     * @return url
     */
    public String getUrl() {
        return url;
    }

    /**
     * the getter for publication date
     * 
     * @return date
     */
    public String getDate() {
        return date;
    }
}
